services:
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
    ports:
      - "4000:4000"
    networks:
      - app_network
    depends_on:
      - database
    links:
      - database

  database:
    image: postgres
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data:
    driver: local
